sudo: required
dist: trusty
language: cpp
install:
  # Set env variables
  - export CC=$CC-$CXX_VERSION
  - export CXX=$CXX-$CXX_VERSION
  # Install conan
  - sudo pip install conan
  - conan install --build=missing

script:
  - mkdir build && cd build
  - cmake .. -DBUILD_TEST=ON -DCMAKE_CXX_COMPILER=$CXX-$CXX_VERSION -DCMAKE_C_COMPILER=$CC-$CXX_VERSION
  - cmake --build .
  - ./bin/test_logs

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CXX_VERSION=5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: CXX_VERSION=6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.6
          packages:
            - clang-3.6
      env: CXX_VERSION=3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
      env: CXX_VERSION=3.8
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env: CXX_VERSION=3.9

