language: cpp
compiler:
  - gcc
  - clang
install:
  # Upgrade GCC
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

  # Install conan
  - sudo pip install conan
  - conan install

script:
  - mkdir build && cd build
  - cmake .. -DBUILD_TEST=ON
  - cmake --build .
  - ./bin/test_logs
