language: cpp
compiler:
  - gcc

install:
  # Upgrade GCC and cmake
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq $CXX-$CXX_VERSION cmake
  - sudo update-alternatives --install /usr/bin/$CC $CC /usr/bin/$CC-$CXX_VERSION 60 --slave /usr/bin/$CXX $CXX /usr/bin/$CXX-$CXX_VERSION
  
  # Install conan
  - sudo pip install conan
  - conan install

script:
  - mkdir build && cd build
  - cmake .. -DBUILD_TEST=ON -DCMAKE_CXX_COMPILER=$CXX-$CXX_VERSION
  - cmake --build .
  - ./bin/test_logs

env:
  - CXX_VERSION=4.9
  - CXX_VERSION=5